Repository GNOME-Nepal/site-server, pull requests merged in 2024-11, with the labels that each got.

#50 FEATURE(event/admin-pannel): complete admin pannel for EVENT
  core/settings.py
  env.example
  event/admin.py
  requirements.txt
Labels: enhancement

#52 feat(log-path): log path is defined in the .env
  core/settings.py
  env.example
Labels: enhancement

#56 Add nightly multi-platform Docker build and push to GitHub Container Registry
  .github/workflows/build_and_push_docker_image.yml
  Dockerfile
Labels: feature

#59 Update codebase for openshift
  .github/workflows/build_and_push_docker_image.yml
  .openshift/secrets.enc.yaml
  .openshift/server.yaml
Labels: enhancement, feature

#62 fix(events/admin): rsvp url and list_display #57
  event/admin.py
Labels: bug, enhancement
