Repository GNOME-Nepal/site-server, pull requests merged in 2024-10, with the labels that each got.

#2 feat(cpanel): setup for cpanel with passenger wsgi
  passenger_wsgi.py
Labels: hacktoberfest-accepted

#3 feat(issue/templates): created a templates for issue
  .github/BUG-REPORT.yml
  .github/FEATURE-REQUEST.yml
  .github/config.yml
  poetry.lock
  pyproject.toml
Labels: hacktoberfest-accepted

#4 Feature/documentation
  readme.md
Labels: hacktoberfest-accepted

#6 feat(update/readme.md): Add installation guide
  readme.md
Labels: hacktoberfest-accepted

#16 Sailesh singh/main
  newsletter/admin.py
  newsletter/migrations/0001_initial.py
  newsletter/migrations/0002_auto.py
  newsletter/migrations/0003_remove_newslettersubscriber_last_sent_and_more.py
  newsletter/migrations/0004_remove_newslettersubscriber_subscription_date.py
  newsletter/models.py
  newsletter/serializers.py
  newsletter/urls.py
  newsletter/views.py
Labels: hacktoberfest-accepted

#17 fix(workflows): Correct typos for CI
  .github/workflows/CI.yml
Labels: hacktoberfest-accepted

#18 docs(assets): Updated Logos, Gifs and Image file for GNOME Nepal
  assets/GNOME Nepal Logo-Animation.gif
  assets/GNOMENepal.png
  assets/Logo.gif
Labels: hacktoberfest-accepted

#19 Update README.md with project documentation and contribution guidelines
  readme.md
Labels: hacktoberfest-accepted

#22 Updated contributing and readme file
  .DS_Store
  .gitignore
  CONTRIBUTING.md
  STYLE_GUIDE.md
  assets/sync_the_fork.png
  readme.md
Labels: documentation, hacktoberfest-accepted, hacktoberfest

#26 fix(issue-template/feature request): made drawback optional
  .github/ISSUE_TEMPLATE/FEATURE-REQUEST.yml
Labels: documentation, enhancement, hacktoberfest-accepted

#30 feat(event/models): initialize
  core/settings.py
  event/__init__.py
  event/admin.py
  event/apps.py
  event/migrations/0001_initial.py
  event/migrations/__init__.py
  event/models.py
  event/tests.py
  event/views.py
Labels: hacktoberfest-accepted, feature, hacktoberfest

#29 docs: reformat document
  CONTRIBUTING.md
  STYLE_GUIDE.md
  readme.md
Labels: documentation, hacktoberfest-accepted, hacktoberfest

#31 Feat/event
  core/settings.py
  event/__init__.py
  event/admin.py
  event/apps.py
  event/migrations/0001_initial.py
  event/migrations/__init__.py
  event/models.py
  event/tests.py
  event/views.py
Labels: hacktoberfest-accepted, feature, hacktoberfest

#33 feat: faq application is setup #32
  .DS_Store
  core/settings.py
  core/urls.py
  faq/__init__.py
  faq/admin.py
  faq/apps.py
  faq/migrations/0001_initial.py
  faq/migrations/__init__.py
  faq/models.py
  faq/serializers.py
  faq/tests.py
  faq/urls.py
  faq/views.py
Labels: hacktoberfest-accepted, hacktoberfest

#34 feat(events/gallery): setup gallery model
  event/migrations/0002_gallery.py
  event/migrations/0003_eventimage_delete_gallery.py
  event/migrations/0004_eventimage_published.py
  event/models.py
  requirements.txt
Labels: hacktoberfest-accepted, hacktoberfest

#37 feat: events
  core/urls.py
  event/admin.py
  event/migrations/0001_initial.py
  event/migrations/0002_gallery.py
  event/migrations/0003_eventimage_delete_gallery.py
  event/migrations/0004_eventimage_published.py
  event/models.py
  event/serializers.py
  event/urls.py
  event/views.py
Labels: hacktoberfest-accepted, hacktoberfest

#38 fix: remove .DS_Store
  .DS_Store
Labels: hacktoberfest-accepted, hacktoberfest

#40 fix: make file init script
  Makefile
Labels: hacktoberfest-accepted, hacktoberfest

#41 fix: remove scripts as it is redudanct here
  scripts/entrypoint.sh
Labels: hacktoberfest-accepted, hacktoberfest

#43 fix: renamed from djate to gnome in make file
  Makefile
Labels: hacktoberfest-accepted, hacktoberfest

#44 feat: update workflow for kubernetes
  .github/workflows/build_and_push_docker_image.yml
Labels: hacktoberfest-accepted, hacktoberfest

#45 fix(log_dir): log dir not found check and create
  core/settings.py
Labels: bug, hacktoberfest-accepted

#47 Feat/text fields
  event/migrations/0002_schedule_description_speaker_description.py
  event/models.py
Labels: enhancement, hacktoberfest-accepted, hacktoberfest
